#Generated by libmep version 2024.4.6.0-beta

import math

def mepx(x, outputs):
  prg = [0] * 100
  prg[0] = x[0]
  prg[1] = x[8]
  prg[2] = x[1]
  prg[3] = x[5]
  prg[4] = prg[3] - prg[3]
  prg[5] = x[5]
  prg[6] = x[0]
  prg[7] = math.sqrt(prg[5])
  prg[8] = x[4]
  prg[9] = x[5]
  prg[10] = x[1]
  prg[11] = math.log(prg[2])
  prg[12] = math.log10(prg[7])
  prg[13] = math.log2(prg[2])
  prg[14] = prg[9] + prg[9]
  prg[15] = math.exp(prg[12])
  prg[16] = math.pow(10, prg[12])
  prg[17] = x[0]
  prg[18] = x[1]
  prg[19] = x[7]
  prg[20] = x[7]
  prg[21] = x[1]
  prg[22] = prg[11] - prg[7]
  prg[23] = prg[12] - prg[16]
  prg[24] = x[6]
  prg[25] = x[5]
  prg[26] = math.log10(prg[0])
  prg[27] = prg[8] * prg[10]
  prg[28] = prg[13] / prg[7]
  prg[29] = math.pow(prg[17], prg[28])
  prg[30] = prg[29] / prg[24]
  prg[31] = prg[16] / prg[14]
  prg[32] = prg[18] if prg[22] < prg[22] else prg[16] # ifalbcd
  prg[33] = x[7]
  prg[34] = x[1]
  prg[35] = 0.378812
  prg[36] = x[5]
  prg[37] = prg[5] if prg[20] < prg[11] else prg[36] # ifalbcd
  prg[38] = math.pow(10, prg[8])
  prg[39] = math.pow(10, prg[21])
  prg[40] = x[3]
  prg[41] = x[0]
  prg[42] = prg[30] / prg[38]
  prg[43] = 0.433171
  prg[44] = prg[19] * prg[16]
  prg[45] = math.exp(prg[23])
  prg[46] = x[4]
  prg[47] = math.log2(prg[14])
  prg[48] = x[6]
  prg[49] = x[6]
  prg[50] = x[2]
  prg[51] = math.sqrt(prg[5])
  prg[52] = x[5]
  prg[53] = prg[37] + prg[14]
  prg[54] = math.log10(prg[21])
  prg[55] = x[7]
  prg[56] = prg[0] / prg[9]
  prg[57] = prg[17] + prg[40]
  prg[58] = x[3]
  prg[59] = math.exp(prg[52])
  prg[60] = x[5]
  prg[61] = math.pow(10, prg[44])
  prg[62] = math.log2(prg[14])
  prg[63] = prg[62] if prg[41] < 0 else prg[11] # ifalzbc
  prg[64] = math.pow(prg[5], prg[22])
  prg[65] = x[2]
  prg[66] = math.exp(prg[19])
  prg[67] = prg[36] * prg[30]
  prg[68] = x[7]
  prg[69] = math.log2(prg[41])
  prg[70] = prg[35] if prg[28] < prg[39] else prg[29] # ifalbcd
  prg[71] = prg[40] / prg[46]
  prg[72] = prg[16] if prg[33] < 0 else prg[39] # ifalzbc
  prg[73] = x[8]
  prg[74] = x[1]
  prg[75] = 0.0525204
  prg[76] = 0.0525204
  prg[77] = prg[51] - prg[29]
  prg[78] = math.pow(10, prg[3])
  prg[79] = x[0]
  prg[80] = x[2]
  prg[81] = x[0]
  prg[82] = math.log(prg[65])
  prg[83] = math.sqrt(prg[51])
  prg[84] = 0.433171
  prg[85] = x[3]
  prg[86] = x[5]
  prg[87] = x[6]
  prg[88] = math.log2(prg[70])
  prg[89] = x[7]
  prg[90] = math.sqrt(prg[19])
  prg[91] = prg[67] if prg[38] < 0 else prg[17] # ifalzbc
  prg[92] = 0.378812
  prg[93] = x[0]
  prg[94] = 0.750549
  prg[95] = prg[27] if prg[68] < 0 else prg[79] # ifalzbc
  prg[96] = math.exp(prg[50])
  prg[97] = x[6]
  prg[98] = prg[97] if prg[26] < 0 else prg[65] # ifalzbc
  prg[99] = math.pow(prg[38], prg[91])

  if prg[30] <= 30.027582:
    outputs[0] = 0
  else:
    outputs[0] = 1

#example of utilization ...

x = [
0.200000, 0.100000, 0.100000, 0.100000, 0.200000, 0.100000, 0.200000, 0.100000, 0.100000]

outputs = [0]

mepx(x, outputs)

print("class = ", int(outputs[0]))
